/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;



/**
 *
 * @author Felipe
 */
public class TelaPrincipal extends javax.swing.JFrame {
    
    
    
    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        
        setSize(816, 537);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTela = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jOpcao = new javax.swing.JMenu();
        jEntrar = new javax.swing.JMenuItem();
        jSair = new javax.swing.JMenuItem();
        jUsuario = new javax.swing.JMenu();
        jCadastrar = new javax.swing.JMenuItem();
        jUsuarios = new javax.swing.JMenuItem();
        jSobre = new javax.swing.JMenu();
        jContato = new javax.swing.JMenuItem();
        jServicos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TanBank");
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/transbank.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 400, 200, 110);

        jTela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/principal2.png"))); // NOI18N
        jTela.setText(" ");
        getContentPane().add(jTela);
        jTela.setBounds(0, 0, 823, 537);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 823, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 537, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 823, 537);

        jOpcao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/computer.png"))); // NOI18N
        jOpcao.setText("Opções");
        jOpcao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jOpcaoActionPerformed(evt);
            }
        });

        jEntrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Entrar.png"))); // NOI18N
        jEntrar.setText("Entrar");
        jEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEntrarActionPerformed(evt);
            }
        });
        jOpcao.add(jEntrar);

        jSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Sair_1.png"))); // NOI18N
        jSair.setText("Sair");
        jSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSairActionPerformed(evt);
            }
        });
        jOpcao.add(jSair);

        jMenuBar1.add(jOpcao);

        jUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Cadastrar.png"))); // NOI18N
        jUsuario.setText("Usuário");

        jCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/user_add.png"))); // NOI18N
        jCadastrar.setText("Cadastrar");
        jCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCadastrarActionPerformed(evt);
            }
        });
        jUsuario.add(jCadastrar);

        jUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/group.png"))); // NOI18N
        jUsuarios.setText("Lista de Usuários");
        jUsuario.add(jUsuarios);

        jMenuBar1.add(jUsuario);

        jSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/information.png"))); // NOI18N
        jSobre.setText("Informações");
        jSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSobreActionPerformed(evt);
            }
        });

        jContato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/email.png"))); // NOI18N
        jContato.setText("Contato");
        jContato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jContatoActionPerformed(evt);
            }
        });
        jSobre.add(jContato);

        jServicos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/text_signature.png"))); // NOI18N
        jServicos.setText("Serviços");
        jServicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jServicosActionPerformed(evt);
            }
        });
        jSobre.add(jServicos);

        jMenuBar1.add(jSobre);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCadastrarActionPerformed
        new TelaCadastro().setVisible(true);
    }//GEN-LAST:event_jCadastrarActionPerformed

    private void jOpcaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jOpcaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jOpcaoActionPerformed

    private void jEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEntrarActionPerformed
        new TelaLogin().setVisible(true);
    }//GEN-LAST:event_jEntrarActionPerformed

    private void jServicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jServicosActionPerformed
       new TelaServicos().setVisible(true);
    }//GEN-LAST:event_jServicosActionPerformed

    private void jSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSairActionPerformed
        
        
        System.exit(0);
    }//GEN-LAST:event_jSairActionPerformed

    private void jSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSobreActionPerformed
        
    }//GEN-LAST:event_jSobreActionPerformed

    private void jContatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jContatoActionPerformed
        new TelaContato().setVisible(true);
    }//GEN-LAST:event_jContatoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jCadastrar;
    private javax.swing.JMenuItem jContato;
    private javax.swing.JMenuItem jEntrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jOpcao;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem jSair;
    private javax.swing.JMenuItem jServicos;
    private javax.swing.JMenu jSobre;
    private javax.swing.JLabel jTela;
    private javax.swing.JMenu jUsuario;
    private javax.swing.JMenuItem jUsuarios;
    // End of variables declaration//GEN-END:variables
}
